version: '3.8'

services:
  playwright:
    build: .
    container_name: playwright_e2e
    ipc: host
    volumes:
      - .:/app
      - /app/node_modules
    tty: true

  nginx:
    image: nginx:alpine
    container_name: playwright_nginx
    ports:
      - "443:443"  # Secure Trace Viewer
      - "444:444"  # Secure HTML Report
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
    depends_on:
      - playwright
