services:
  playwright-runner:
    build:
      context: .
      dockerfile: Dockerfile.playwright
    container_name: playwright-daily-runner
    environment:
      TZ: ${TZ:-America/New_York}
      RESULTS_ROOT: /test-results
    volumes:
      - ./test-results:/test-results

  report-server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: playwright-report-server
    environment:
      TZ: ${TZ:-America/New_York}
      RESULTS_ROOT: /test-results
      PORT: 3000
    # expose:
    #   - "3000"
    ipc: host
    volumes:
      - ./test-results:/test-results:ro
    ports:
      - "3000:3000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    depends_on:
      - report-server
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro
      - ./test-results:/test-results:ro
    restart: unless-stopped
